fields:
- caption: Scaling Strategy
  type: list
  name: loadGrowth
  default: slow
  required: true
  values:        
    - value: slow
      caption: Low Load
      tooltip: <h2>Low load scaling strategy</h2>add 1 new node when CPU > 70% <p>remove when CPU < 20%</p>
    - value: medium
      caption: Medium Load
      tooltip: <h3>Medium load scaling strategy</h3>add 1 new node when CPU > 50% <p>remove when CPU < 20%</p>
    - value: fast
      caption: High Load
      tooltip: <h3>High load scaling strategy</h3>add 2 new nodes when CPU > 30% <p>remove when CPU < 10%</p>

- caption: Advanced Features
  type: displayfield
  name: displayfield
  markup:
