fields:
- caption: Scaling Load Growth
  type: list
  name: loadGrowth
  default: slow
  required: true
  values:        
    - value: slow
      caption: Slow
      tooltip: <h3>Master-Master with Extra Slaves</h3>Pre-configured replication with two interconnected master databases. While horizontal scaling the cluster is extended with additional slave nodes."
    - value: medium
      caption: Medium
    - value: fast
      caption: Fast

- caption: Advanced Features
  type: displayfield
  name: displayfield
  markup:
