fields:
- caption: Scaling Strategy
  type: list
  name: loadGrowth
  default: slow
  required: true
  values:        
    - value: slow
      caption: Low Load
      tooltip: <h3>Low Load</h3>add new node when CPU > 70%, remove when CPU < 20%"
    - value: medium
      caption: Medium Load
      tooltip: <h3>Medium Load</h3>add new node when CPU > 70%, remove when CPU < 20%"
    - value: fast
      caption: High Load
      tooltip: <h3>High Load</h3>add new node when CPU > 70%, remove when CPU < 10%"

- caption: Advanced Features
  type: displayfield
  name: displayfield
  markup:
