fields:
- caption: Scaling Strategy
  type: list
  name: loadGrowth
  default: slow
  required: true
  values:        
    - value: slow
      caption: Low Load
      tooltip: <h2>Low load scaling strategy</h2>add new node when <h3>CPU > 70%</h3> <p> remove when <h3>CPU < 20%</h3></p>
    - value: medium
      caption: Medium Load
      tooltip: <h3>Medium load scaling strategy</h3>add new node when CPU > 70%, remove when CPU < 20%"
    - value: fast
      caption: High Load
      tooltip: <h3>High load scaling strategy</h3>add new node when CPU > 70%, remove when CPU < 10%"

- caption: Advanced Features
  type: displayfield
  name: displayfield
  markup:
