fields:
- caption: Regions
  type: regionlist
  name: regions
  disableInactive: true
  selectFirstAvailable: true
  multiSelect: false

- caption: Environment
  type: envname
  name: envName
  dependsOn: region
  randomName: true
  showFullDomain: false
  required: true
    
- caption: Advanced Features
  type: displayfield
  name: displayfield
  markup:
